general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_jen.csv'
  catalog_type: 'CSV'
  append_data_to_catalog: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/waypoints/scidata_20180610.csv'
  image_type: 'JPG'
  sampling:
    - mode: 'percent'
      params:
        value: 0.1
  convert:
    - mode: 'bits'
      params:
        output_bits: 8
    - mode: 'to'
      params:
        to: 'gray'
