general:
  sample_data: 'pelagic_csv'
  output_path: './output'
  image_type: 'BMP'
  sampling:
    - mode: 'percent'
      params:
        value: 0.9
  convert:
    - mode: 'bits'
      params:
        output_bits: 8

steps:
  - color:
      name: 'deblur'
      mode: 'deblur'
      test: False
      step_name: 'deblur'
      params:
        method: 'wiener'
        psf_type: 'gaussian'
        sigma: 1
        angle: 45
