general:
  sample_data: 'benthic_csv'
  output_path: './output'
  sampling:
    - mode: 'percent'
      params:
        value: 0.9
  convert:
    - mode: 'bits'
      params:
        output_bits: 8

steps:
  - sampling:
      name: 'overlapping'
      mode: 'overlapping'
      test: True
      params:
        theta: 40
        omega: 57
        camera_distance: 1.12
        threshold: 0.5
