general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/mojtaba/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examles/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_mojtaba.csv'
  catalog_type: 'CSV' # choose between IFDO, CSV, SQL, etc
  # file_name_pattern: '*0000*'
  image_type: 'BMP' # choose between BMP, RAW, PNG, JPEG, TIFF, etc
  convert_bits: 8  # Use 8 for 8-bit images, 16 for 16-bit images
  convert_autoscale: True
  convert_channel_selector: -1
  sampling_mode: 'percent'  # choose 'fixed' or 'percent'
  sampling_limits: 0.9

steps:
#  - color:
#      name: 'edge_detection'
#      mode: 'edge_detection'
#      method: 'scharr'
#      object_type: "isolated"
#      object_selection: 'Largest Area'
#      blur_radius: 3
#      threeshold: [2.5 3.0]
#      deconv: True
#      deconv_method: 'LR'
#      deconv_iter: 7
#      deconv_mask_weight: 0.5
#      estimate_sharpness: True
#      small_float_val: 0.0001

  - color:
      name: 'contrast_adjustment'
      mode: 'contrast_adjustment'
      method: 'gamma' # choose between ahe (Adaptive Histogram Equalization) or gamma
      kernel_size: None # [x, y] or None By default, ``kernel_size`` is 1/8 of ``image`` height by 1/8 of its width.
      clip_limit: 0.01 # Clipping limit, normalized between 0 and 1 (higher values give more contrast).
      gamma_value: 0.8 # For greater than 1, image will be darker, For less than 1, image will be brighter.

  # - color:
  #     name: 'sharpen'
  #     mode: 'sharpen'
  #     limits: [2.0, 2.0]