general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/mojtaba/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examles/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_mojtaba.csv'
  catalog_type: 'CSV' # choose between IFDO, CSV, SQL, etc
  # file_name_pattern: '*0000*'
  image_type: 'BMP' # choose between BMP, RAW, PNG, JPEG, TIFF, etc
  convert_bits: 8  # Use 8 for 8-bit images, 16 for 16-bit images
  convert_autoscale: True
  convert_channel_selector: -1
  sampling_mode: 'percent'  # choose 'fixed' or 'percent'
  sampling_limits: 0.9

steps:
#  - color:
#      name: 'edge_detection'
#      mode: 'edge_detection'
#      method: 'scharr'
#      object_type: "isolated"
#      object_selection: 'Largest Area'
#      blur_radius: 3
#      threeshold: [2.5 3.0]
#      deconv: True
#      deconv_method: 'LR'
#      deconv_iter: 7
#      deconv_mask_weight: 0.5
#      estimate_sharpness: True
#      small_float_val: 0.0001

#  - color:
#      name: 'contrast_adjustment'
#      mode: 'contrast_adjustment'
#      method: 'gamma' # choose between clahe (Contrast Limited Adaptive Histogram Equalization (CLAHE)) or gamma
#      kernel_size: None # [x, y] or None By default, ``kernel_size`` is 1/8 of ``image`` height by 1/8 of its width.
#      clip_limit: 0.01 # Clipping limit, normalized between 0 and 1 (higher values give more contrast).
#      gamma_value: 0.8 # For greater than 1, image will be darker, For less than 1, image will be brighter.

#  - color:
#      name: 'illumination_correction'
#      mode: 'illumination_correction'
#      method: 'rolling' # choose between rolling (rolling bar algorithm)
#      radius: 100 # default=100, Radius of a ball-shaped kernel to be rolled/translated in the image.

  - color:
      name: 'deblur'
      mode: 'deblur'
      method: 'wiener' # choose between wiener or
      psf_type: 'gaussian' # choose between gaussian (used to model out-of-focus blur) or motion (linear motion blur)
      sigma: 1 # estimated sigma for the Gaussian (1 to 3 — for slight blur, 3 to 5 — for moderate blurring, and  5 to 10+ — for strong blur)
               # or estimated length of motion blur (5 to 10 pixels — where slight movement, 10 to 20 pixels — Moderate camera shake, and 20 to 50+ pixels — Significant motion blur)
      size: 25 #the dimensions of the PSF

  # - color:
  #     name: 'sharpen'
  #     mode: 'sharpen'
  #     limits: [2.0, 2.0]