general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/'
  metadata_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/metadata/metadata_benthic.csv'
  metadata_type: 'CSV_FILE'
  append_data_to_metadata: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/waypoints/scidata_20180610.csv'
  image_type: 'JPG'
  rename: 'datetime'
  sampling:
    - mode: 'percent'
      params:
        value: 0.1
  convert:
    - mode: 'bits'
      params:
        output_bits: 8
    - mode: 'to'
      params:
        to: 'gray'
