general:
  sample_data: 'benthic_ifdo'
  output_path: './output'
  n_jobs: 8
  sampling:
    - mode: 'percent'
      params:
        value: 0.2
  convert:
    - mode: 'bits'
      params:
        output_bits: 8
steps:
  - color:
      name: 'color_correction'
      mode: 'grayscale'
  
  - sampling:
      name: 'datetime'
      mode: 'datetime'
      params:
        min: '2016-05-11 04:14:00'
        max: '2016-05-11 09:27:00'

  - sampling:
      name: 'overlapping'
      mode: 'overlapping'
      params:
        theta: 40
        omega: 57
        threshold: 0.5

  - color:
      name: 'color_correction'
      mode: 'gaussian_blur'
      params:
        sigma: 1.0

  - color:
      name: 'sharpen'
      mode: 'sharpen'
      params:
        alpha: 1.5
        beta: -0.5

  - color:
      name: 'contrast'
      mode: 'contrast'

