general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/mojtaba/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examles/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_mojtaba.csv'
  catalog_type: 'CSV' # choose between IFDO, CSV, SQL, etc
  # file_name_pattern: '*0000*'
  image_type: 'BMP' # choose between BMP, RAW, PNG, JPEG, TIFF, etc
  sampling:
    - mode: 'percent'
      params:
        value: 0.9
  convert:
    - mode: 'bits'
      params:
        output_bits: 8
        autoscale: True

steps:
  - color:
      name: 'edge_detection'
      mode: 'edge_detection'
      params:
        method: 'scharr'
        object_type: "isolated"
        object_selection: 'Largest Area'
        blur_radius: 3
        threshold: [2.5 3.0]
        deconv: True
        deconv_method: 'LR'
        deconv_iter: 7
        deconv_mask_weight: 0.5
        estimate_sharpness: True
        small_float_val: 0.0001

  # - color:
  #     name: 'sharpen'
  #     mode: 'sharpen'
  #     limits: [2.0, 2.0]