general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/mojtaba/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examles/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_mojtaba.csv'
  catalog_type: 'CSV'
  image_type: 'BMP'
  sampling:
    - mode: 'percent'
      params:
        value: 0.9
  convert:
    - mode: 'bits'
      params:
        output_bits: 8

steps:
  - color:
      name: 'deblur'
      mode: 'deblur'
      params:
        method: 'wiener'
        psf_type: 'gaussian'
        sigma: 1
        angle: 45
