general:
  input_path: 'SAMPLE_DATA_BENTHIC'
  output_path: './output'
  metadata_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/metadata/metadata_benthic.csv'
  metadata_type: 'CSV_FILE'
  append_data_to_metadata: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/waypoints/scidata_20180610.csv'
  image_type: 'JPG'
  sampling:
    - mode: 'percent'
      params:
        value: 0.3

  convert:
    - mode: 'bits'
      params:
        output_bits: 8

steps:
  - sampling:
      name: 'overlapping'
      mode: 'overlapping'
      test: True
      params:
        theta: 40
        omega: 57
        threshold: 0.5
