general:
  input_path: "/mnt/noc/code/paidiver/paidiverpy/examples/example_notebooks/output"
  output_path: "/mnt/noc/code/paidiver/paidiverpy/examples/example_notebooks/output2"
  metadata_path: "/mnt/noc/code/paidiver/paidiverpy/examples/example_notebooks/metadata.csv"
  metadata_type: "CSV_FILE"
  image_open_args: "PNG"
  convert:
    - mode: "normalize"
      params:
        min: 0
        max: 255
        method: "minmax"