general:
  append_data_to_metadata: /mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/waypoints/scidata_20180610.csv
  convert:
  - mode: bits
    params:
      output_bits: 8
  image_type: JPG
  input_path: /mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen
  metadata_path: /mnt/code/code/noc/paidiver/paidiverpy/examples/metadata/metadata_benthic.csv
  metadata_type: CSV_FILE
  n_jobs: 1
  name: raw
  output_path: /mnt/code/code/noc/paidiver/paidiverpy/examples/data
  rename: datetime
  sampling:
  - mode: percent
    params:
      value: 0.1
  step_name: raw
steps:
- color:
    mode: grayscale
    name: gray
    test: false
