general:
  client:
    cluster_type: local
    params:
      memory_limit: 8GB
      n_workers: 8
      threads_per_worker: 8
  convert:
  - mode: bits
    params:
      output_bits: 8
  n_jobs: 2
  output_path: ./output
  sample_data: benthic_ifdo
  track_changes: false
steps:
- colour:
    mode: grayscale
    name: colour_correction
- sampling:
    mode: datetime
    name: datetime
    params:
      max: '2016-05-11 09:27:00'
      min: '2016-05-11 04:14:00'
- colour:
    mode: gaussian_blur
    name: colour_correction
    params:
      sigma: 1.0
- colour:
    mode: sharpen
    name: sharpen
    params:
      alpha: 1.5
      beta: -0.5
- colour:
    mode: contrast
    name: contrast
