name: Paidiverpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy=2.0.1
  - pandas=2.2.2
  - pathlib=1.0.1
  - pillow=10.4.0
  - scikit-image=0.24.0
  - scipy=1.14.0
  - tqdm=4.66.5
  - pyyaml=6.0.2
  - openpyxl=3.1.5
  - shapely=2.0.5
  - geopy=2.2.0
  - graphviz=12.0.0
  - geopandas=1.0.1
  - exempi=2.4.3
  - panel>=1.4.5
  - dask-image==2024.5.3
  - dask>=2024.9.0
  - distributed>=2024.9.0
  - jsonschema>=4.23.0
  - matplotlib>=3.5.0
  - ipython>=8.26.0
  - mariqt>=0.6.12
  - unzip=6.0
  - libgl
  - libegl
  - libopengl
  - pip
  - setuptools>=64.0.0
  - wheel
  - pytest>=7.2.0

  - pip:
    - opencv-python>=4.10.0.84
    - mariqt>=0.6.12
