name: Paidiverpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy=2.0.1
  - pandas=2.2.2
  - pathlib=1.0.1
  - pillow=10.4.0
  - scikit-image=0.24.0
  - scipy=1.14.0
  - tqdm=4.66.5
  - pyyaml=6.0.2
  - openpyxl=3.1.5
  - shapely=2.0.5
  - geopy=2.2.0
  - graphviz=12.0.0
  - geopandas=1.0.1
  - exempi=2.4.3
  - unzip=6.0
  - libgl
  - libegl
  - libopengl
  - ipython
  - ipykernel
  - pip
  - setuptools>=42
  - wheel
  - pytest>=7.2.0

  - pip:
    - opencv-python>=4.10.0.84
    - mariqt>=0.6.12
