name: Paidiverpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - numpy>=2.0.0
  - pandas>=2.2.2
  - pathlib>=1.0.1
  - pillow>=10.3.0
  - scikit-image>=0.24.0
  - scipy>=1.13.1
  - tqdm>=4.66.4
  - pyyaml>=6.0.1
  - openpyxl>=3.0.9
  - shapely>=2.0.5
  - geopy>=2.4.1
  - graphviz>=0.20.3
  - geopandas>=1.0.1
  - exempi>=2.5.0
  - unzip>=0.1.0
  - libglu1-mesa-glx
  - libgl
  - libegl
  - libopengl
  - ipython
  - ipykernel
  - pip
  - setuptools>=42
  - wheel
  - pytest>=7.2.0

  - pip:
    - opencv-python>=4.10.0.84
    - mariqt>=0.6.12
