
sampling:
  path_input: 'D:\mojmas\files\Projects\PAIDIVER\data\uvp5'
  path_output: 'D:\mojmas\files\Projects\PAIDIVER\data'
  image_type: 'UVP5'          # choose 'UVP5'
  sampling_method: 'percent'  # choose 'fixed' or 'percent'
  sampling_percent: 0.1
  target_size: [227, 227]  #image target size
  cutting_ruler: False
  invert_img: False

cv_attribute:
  name: 'Default-Settings'
  version: 201
  description: 'Default processing settings for image import'
  file_name_fmt: 'PTVR'
  edge_threshold_low: 2.5
  edge_threshold_high: 3
  edge_detector: 'Scharr'
  downsample_factor: 1
  channel_selector: -1
  object_selection: 'Largest Area'
  is_raw: True
  is_bayer_pattern: True
  autoscale: True
  deconv: True
  deconv_method: 'LR'
  deconv_iter: 7
  deconv_mask_weight: 0.5
  estimate_sharpness: True
  small_float_val: 0.0001
  bw_blur_radius: 3
  bayer_pattern: 'RG'
  channels: 1  # Use 1 for grayscale images, 3 for RGB images

preprocessing:
  denoise: True

