general:
  input_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/'
  output_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/'
  catalog_path: '/mnt/code/code/noc/paidiver/paidiverpy/examples/catalog/catalog_jen.csv'
  catalog_type: 'CSV'
  append_data_to_catalog: '/mnt/code/code/noc/paidiver/paidiverpy/examples/data/jen/waypoints/scidata_20180610.csv'
  # file_name_pattern: '*0000*'
  image_type: 'JPG' # choose between BMP, RAW, PNG, JPEG, TIFF, etc
  sampling:
    - mode: 'percent'
      params:
        value: 0.2

  convert:
    - mode: 'bits'
      params:
        output_bits: 8

steps:

#   - sampling:
#       name: 'altitude_selection'
#       mode: 'altitude'
#       limits: 1.5
#       test: True

  - sampling:
      name: 'overlapping'
      mode: 'overlapping'
      test: True
      params:
        theta: 40
        omega: 57
        threshold: 0.5
  # - sampling:
  #     name: 'Area'
  #     mode: 'region'
  #     limits: '/mnt/code/code/noc/paidiver/paidiverpy/data/polygons/region_polygon.geojson'
  #     test: True

  # - sampling:
  #     name: 'Area'
  #     mode: 'region'
  #     limits: '/mnt/code/code/noc/paidiver/paidiverpy/data/polygons/region_polygon.shp'
  #     test: True

  # - sampling:
  #     name: 'Area'
  #     mode: 'region'
  #     limits: [-153.6050, -153.6044, 11.2516, 11.2518]
  #     # limits: [-153.609, -153.608, 11.2516, 11.2518]
  #     test: True

  # - sampling:
  #     name: 'datetime'
  #     mode: 'datetime'
  #     limits: ['2018-06-11 04:14:00', '2018-06-11 04:20:00']
  #     test: True


  # - sampling:
  #     name: 'pitch_roll'
  #     mode: 'pitch_roll'
  #     limits: [0, 1.9]
  #     test: False

  # - sampling:
  #     name: 'altitude'
  #     mode: 'altitude'
  #     limits: 1.9
  #     test: False

  # - sampling:      
  #     name: 'obscure'
  #     mode: 'obscure'
  #     limits: [40, 100]
  #     test: True


  # - sampling:      
  #     name: 'region'
  #     mode: 'region'
  #     limits: [0, 1.9]
  #     file_path: '/mnt/code/code/noc/paidiver/paidiverpy/data/jen/waypoints/scidata_20180610.csv'
  #     test: True

  # - sampling:
  #     name: 'altitude'
  #     mode: 'altitude'
  #     cutting_ruler: False
  #     invert_img: False
  #     downsample_factor: 1
  #     edge_threshold_low: 2.5
  #     edge_threshold_high: 3
  #     edge_detector: 'Scharr'
  #     bw_blur_radius: 3
  #     trim_transects: [4, True]
  #     trim_altitude: [1.9, True]
  #     trim_pitch_rollL: [1.9, True]
  #     trim_overlapping_theta: 40
  #     trim_overlapping_omega: 57

  # - edge:
  #     name: 'edge_detection'
  #     object_selection: 'Largest Area'
  #     deconv: True
  #     deconv_method: 'LR'
  #     deconv_iter: 7
  #     deconv_mask_weight: 0.5
  #     estimate_sharpness: True
  #     small_float_val: 0.0001

# position:
  # waypoint_format: 'YAML'
  # waypoint_folder_path: '/mnt/code/code/noc/paidiver/paidiverpy/data/jen/waypoints/'
  # waypoint_data_pattern: '*.yml'
