name: Create Conda Meta File

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-activate-base: true

      - name: Install Conda dependencies
        shell: bash -el {0}
        run: |
          conda install -y -c conda-forge conda-smithy conda-build toml jinja2

      - name: Run Python script to generate meta.yml
        shell: bash -el {0}
        run: |
          python conda_recipes/generate_conda_meta.py
          python conda_recipes/generate_conda_meta.py --bioconda

      - name: Validate Conda recipe
        shell: bash -el {0}
        run: |
          conda-smithy recipe-lint conda_recipes/

      - name: Commit and Push Changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Working on branch: $BRANCH_NAME"

          if ! git diff --quiet -- conda_recipes/meta_bioconda.yaml conda_recipes/meta.yaml; then
            git add conda_recipes/meta_bioconda.yaml conda_recipes/meta.yaml
            git commit -m "chore: update conda recipe"
            git pull --rebase origin "$BRANCH_NAME"
            git push origin HEAD:"$BRANCH_NAME"
          else
            echo "No changes to commit."
          fi
