name: Build and Publish Docker Image

on:
  push:
    # branches:
    #   - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set image tags
        run: |
          IMAGE_NAME="paidiver/paidiverpy"  # Remove the GitHub username for Docker Hub
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase
          IMAGE_TAG=${{ github.sha }}  # Unique tag for commit
          LATEST_TAG="latest"

          # Define separate names for GHCR and Docker Hub
          GHCR_IMAGE="ghcr.io/${{ github.repository }}"
          DOCKERHUB_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/paidiverpy"  # Set correct Docker Hub image name

          echo "GHCR_IMAGE=$GHCR_IMAGE" >> $GITHUB_ENV
          echo "DOCKERHUB_IMAGE=$DOCKERHUB_IMAGE" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME_LOWER }} .

      - name: Tag Image for GHCR and Docker Hub
        run: |
          docker tag ${{ env.IMAGE_NAME_LOWER }} ${{ env.GHCR_IMAGE }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_NAME_LOWER }} ${{ env.GHCR_IMAGE }}:${{ env.LATEST_TAG }}
          docker tag ${{ env.IMAGE_NAME_LOWER }} ${{ env.DOCKERHUB_IMAGE }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_NAME_LOWER }} ${{ env.DOCKERHUB_IMAGE }}:${{ env.LATEST_TAG }}

      - name: Push to GitHub Container Registry
        run: |
          docker push ${{ env.GHCR_IMAGE }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.GHCR_IMAGE }}:${{ env.LATEST_TAG }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKERHUB_IMAGE }}:${{ env.LATEST_TAG }}

      - name: Log out from Registries
        run: |
          docker logout ghcr.io
          docker logout docker.io
