name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create conda environment
      run: |
        conda env create -f environment.yml
        echo "conda activate Paidiverpy" >> ~/.bashrc
        source ~/.bashrc
        pip install --upgrade pip
        pip install .
        pip install build twine wheel requests

    - name: Extract Package Version
      run: echo "PACKAGE_VERSION=$(python -c 'import paidiverpy; print(paidiverpy.__version__)')" >> $GITHUB_ENV

    - name: Check if version exists on PyPI
      run: |
        PACKAGE_NAME="paidiverpy"
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/$PACKAGE_NAME/${{ env.PACKAGE_VERSION }}/json)

        if [ "$RESPONSE" -eq 200 ]; then
          echo "Version $PACKAGE_VERSION already exists on PyPI. Skipping upload."
          echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
        else
          echo "Version $PACKAGE_VERSION does not exist. Proceeding with upload."
          echo "SKIP_UPLOAD=false" >> $GITHUB_ENV

    - name: Build Package
      if: env.SKIP_UPLOAD == 'false'
      run: python -m build

    - name: Publish to PyPI
      if: env.SKIP_UPLOAD == 'false'
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload dist/* --verbose

  zenodo:
    needs: release
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Zenodo Archival
      if:
