name: Run tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-inc/github-action@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create conda environment
        run: |
          conda env create -f environment.yml
          conda activate Paidiverpy

      - name: Test with pytest
        run: |
          pytest tests/
